// <auto-generated />
namespace PRSserver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class finishedallmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finishedallmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281749039_finished all models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
